# 基础ros设置
sub_cloud_topic : "abc"
pub_cloud_topic : "efg"
# 降采样大小
filterRes : 0.05
# 设置roi区域
roi:
  min_x : 0
  max_x : 20
  min_y : -20
  max_y : 20
  min_z : -1
  max_z : 3
# 去除屋顶的点云（车辆相关点云）
roof:
  min_x : -1
  max_x : 1
  min_y : -1
  max_y : 1
  min_z : -2
  max_z : 2
# 设置Ransac的参数
ransac:
  maxIterations : 250
  distanceThreshold : 0.1
# 设置聚类参数
cluster:
  clusterTolerance : 0.2
  minsize : 30
  maxsize : 1000
# 可视化分割地面点云
view:
  segment : false
  
