# 基础ros设置
sub_image_topic : "/usb_cam/image_raw"
sub_pointcloud_topic : "/livox/lidar_192_168_20_105"
pub_image_topic : "detect_img"
pub_image_raw_topic : "image_raw"
pub_lidar_topic : "detect_lidar"
pub_cloud_noground_topic : "cloud_noground"
pub_box3d_markers_topic : "/box3d_markers"

# 使用仿真还是激光雷达
# 使用仿真就是图像数据从功能包接收
# 不使用仿真就是图像数据从/dev驱动中读取
use_bag : true
camera_image_dev : "/dev/video11"

# 大于一定距离就不计算到电梯拥挤度里面 ,单位 m
person_distance : 5
# 订阅的开启/关闭电梯拥挤度的话题
detect_congest_enable_topic : "/detect_congest_enable"
# 发布的电梯拥挤度话题
person_density_topic : "/person_density"
# 发布的电梯拥挤度话题（指定roi排除掉镜像人员)
person_density_withroi_topic : "/person_density_withroi"
# 发布的电梯拥挤度话题（ 融合yolo和点云的数据 )
person_density_fusion_topic : "/person_density_fusion"
# 电梯拥挤度roi筛选（大于这个置信度才进行后续的roi筛选） (设置成1.0就认为不筛选置信度了)
person_density_roi_confidence : 0.6
# 电梯拥挤度检测，排除掉镜像人员，指定roi区域 （长方形区域，基于车体坐标系）
person_density_roi:
  x_min: 0 
  x_max: 1.95
  y_min: -0.7
  y_max: 0.7
# 发布的障碍物信息话题
obstacles_topic_ : "/obstacles"

# 设置传感器时间同步最大时间间隔 单位s
max_time_interval : 0.1

# 点云是否去除地面(去除地面最好开启点云降采样)
remove_ground_points_enable : true
# 去除地面点云高度
remove_ground_height : 0.1
# 最大迭代次数
max_iterations : 400

# 图像是否去畸变,会增加约12ms耗时
img_distort_enable : true
# 点云降采样大小,单位 m,小于等于0就是不降采样
leaf_size : 0.02

# 点云dbscan聚类
cluster :
  octreeResolution : 1
  minPtsAux : 20
  epsilon : 0.08
  minPts : 5
  # 欧式聚类
  cluster_tolerance : 0.08
  min_cluster_size : 10
  max_cluster_size : 9999

# obb multiple threads
obb_omp_threads : 4

# 点云在多大范围投影到相机平面上(数值单位m,坐标系是激光坐标系)
lidar2camera:
  min_x : 0
  max_x : 20
  min_y : -20
  max_y : 20
  min_z : -20
  max_z : 20


# 激光雷达到车体坐标系变换
convert_lidar2car:
  transform:
    x: 0.3643
    y: 0.2078
    z: 1.21
  # 角度，代码里会转成弧度
  rotation :
    roll: -179.5
    pitch: 0.5
    yaw: 360

# 相机到激光雷达坐标系是使用matrix还是用欧拉角
if_use_matrix : true
# 相机到激光雷达坐标系变换
convert_carmera2lidar_matrix: [ 9.8926083033897869e-02, 9.9507023727951061e-01,
       6.9894904012135772e-03, -4.2821240081363088e-01,
       -2.5562146328092408e-02, -4.4804609003203655e-03,
       9.9966319435358919e-01, 6.4979552549797051e-02,
       9.9476640814347539e-01, -9.9071430546949363e-02,
       2.4992896565013255e-02, 1.2746014762805993e-01, 0., 0., 0., 1. ]


# 相机到激光雷达坐标系变换
# convert_carmera2lidar:
#   transform:
#     x: -0.01276627371659704
#     y: 1.040611755008172
#     z: 0.2783443893841093
#   # 角度，代码里会转成弧度
#   rotation :
#     yaw: 4.491111184694372
#     pitch: -1.475459526983985
#     roll: 0.2987467915697319

# 相机畸变参数
camera_distort_params:
  p0: 0.023724
  p1: -0.059681
  p2: 0.001333
  p3: -0.000242
  p4: 0

  # 输入图片尺寸
image:
  width: 1280
  height: 720
# 相机内参矩阵
camera_in_param:
  dx: 761.935083
  dy: 762.207359
  u0: 607.825958
  v0: 357.643751

# 启动时warmup并生成测试
warmup: false
# 生成debug图片
# write_img: false
